version: '3.5'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    environment:
      - DATABASE_URL=sqlite:///./admin.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./app:/app/app
    ports:
      - "8002:8000"  # FastAPI accessible on host:8002 with aapnel domain
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
