version: '3'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./app:/app/app
    networks:
      - web_network

  nginx:
    image: nginx:latest
    container_name: nginx_fastapi
    ports:
      - "8080:80"
      - "8443:443"  # Changed from 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - fastapi
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
